In [1]:
import pandas as pd 
import numpy as np

In [2]:
train= pd.read_csv("Downloads/day_34/day_34/av_loan_u6lujuX_CVtuZ9i.csv")
test= pd.read_csv("Downloads/day_34/day_34/av_loan_test_Y3wMUE5_7gLdaTN.csv")
train.head(3)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
Loan_ID              614 non-null object
Gender               601 non-null object
Married              611 non-null object
Dependents           599 non-null object
Education            614 non-null object
Self_Employed        582 non-null object
ApplicantIncome      614 non-null int64
CoapplicantIncome    614 non-null float64
LoanAmount           592 non-null float64
Loan_Amount_Term     600 non-null float64
Credit_History       564 non-null float64
Property_Area        614 non-null object
Loan_Status          614 non-null object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.4+ KB

In [4]:
train.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [5]:
train['Gender'].unique()

array(['Male', 'Female', nan], dtype=object)

In [6]:
train= pd.read_csv("Downloads/day_34/day_34/av_loan_u6lujuX_CVtuZ9i.csv").replace("Male",0).replace("Female",1).replace('Unknown',2).\
       replace("Yes",0).replace("No",1).replace('0',0).replace('1',1).replace('2',2).replace('3+',3).replace('Graduate',0).replace('Not Graduate',1).replace('Yes',0).\
       replace('No',1).replace('Urban',0).replace('Rural',1).replace('Semiurban',2).replace('Y',0).replace('N',1)

X = train.iloc[:,1:-1]
y = train.iloc[:,-1]

In [7]:
from sklearn.preprocessing import Imputer

imp = Imputer(missing_values='NaN', strategy='mean', axis=0)
imp.fit(X)

X_columns = X.columns.values
X = pd.DataFrame(imp.transform(X), columns=X_columns)

C:\Users\apple\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

In [8]:
X.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,0.0,1.0,0.0,0.0,1.0,5849.0,0.0,146.412162,360.0,1.0,0.0
1,0.0,0.0,1.0,0.0,1.0,4583.0,1508.0,128.000000,360.0,1.0,1.0
2,0.0,0.0,0.0,0.0,0.0,3000.0,0.0,66.000000,360.0,1.0,0.0
3,0.0,0.0,0.0,1.0,1.0,2583.0,2358.0,120.000000,360.0,1.0,0.0
4,0.0,1.0,0.0,0.0,1.0,6000.0,0.0,141.000000,360.0,1.0,0.0

In [9]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 11 columns):
Gender               614 non-null float64
Married              614 non-null float64
Dependents           614 non-null float64
Education            614 non-null float64
Self_Employed        614 non-null float64
ApplicantIncome      614 non-null float64
CoapplicantIncome    614 non-null float64
LoanAmount           614 non-null float64
Loan_Amount_Term     614 non-null float64
Credit_History       614 non-null float64
Property_Area        614 non-null float64
dtypes: float64(11)
memory usage: 52.8 KB

In [10]:
train.dtypes

Loan_ID               object
Gender               float64
Married              float64
Dependents           float64
Education              int64
Self_Employed        float64
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area          int64
Loan_Status            int64
dtype: object

In [11]:
X.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,0.0,1.0,0.0,0.0,1.0,5849.0,0.0,146.412162,360.0,1.0,0.0
1,0.0,0.0,1.0,0.0,1.0,4583.0,1508.0,128.000000,360.0,1.0,1.0
2,0.0,0.0,0.0,0.0,0.0,3000.0,0.0,66.000000,360.0,1.0,0.0
3,0.0,0.0,0.0,1.0,1.0,2583.0,2358.0,120.000000,360.0,1.0,0.0
4,0.0,1.0,0.0,0.0,1.0,6000.0,0.0,141.000000,360.0,1.0,0.0

In [12]:
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Loan_Status, dtype: int64

In [13]:
test['Gender'].unique()

array(['Male', 'Female', nan, 'Unknown'], dtype=object)

In [14]:
test = pd.read_csv("Downloads/day_34/day_34/av_loan_test_Y3wMUE5_7gLdaTN.csv").replace("Male",0).replace("Female",1).replace('Unknown',2).\
       replace("Yes",0).replace("No",1).replace('0',0).replace('1',1).replace('2',2).replace('3+',3).replace('Graduate',0).replace('Not Graduate',1).replace('Yes',0).\
       replace('No',1).replace('Urban',0).replace('Rural',1).replace('Semiurban',2).replace('Y',0).replace('N',1)
X_s = test.iloc[:,1:]

In [15]:
test.dtypes

Loan_ID               object
Gender               float64
Married                int64
Dependents           float64
Education              int64
Self_Employed        float64
ApplicantIncome        int64
CoapplicantIncome      int64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area          int64
dtype: object

In [16]:
X_s.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,0.0,0,0.0,0,1.0,5720,0,110.0,360.0,1.0,0
1,0.0,0,1.0,0,1.0,3076,1500,126.0,360.0,1.0,0
2,0.0,0,2.0,0,1.0,5000,1800,208.0,360.0,1.0,0
3,0.0,0,2.0,0,1.0,2340,2546,100.0,360.0,NaN,0
4,0.0,1,0.0,1,1.0,3276,0,78.0,360.0,1.0,0

In [17]:
X_s = X_s.reindex(X_columns, axis=1)
X_s.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,0.0,0,0.0,0,1.0,5720,0,110.0,360.0,1.0,0
1,0.0,0,1.0,0,1.0,3076,1500,126.0,360.0,1.0,0
2,0.0,0,2.0,0,1.0,5000,1800,208.0,360.0,1.0,0
3,0.0,0,2.0,0,1.0,2340,2546,100.0,360.0,NaN,0
4,0.0,1,0.0,1,1.0,3276,0,78.0,360.0,1.0,0

In [18]:
X_s = pd.DataFrame(imp.transform(X_s), columns=X_columns)
X_s.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,0.0,0.0,0.0,0.0,1.0,5720.0,0.0,110.0,360.0,1.000000,0.0
1,0.0,0.0,1.0,0.0,1.0,3076.0,1500.0,126.0,360.0,1.000000,0.0
2,0.0,0.0,2.0,0.0,1.0,5000.0,1800.0,208.0,360.0,1.000000,0.0
3,0.0,0.0,2.0,0.0,1.0,2340.0,2546.0,100.0,360.0,0.842199,0.0
4,0.0,1.0,0.0,1.0,1.0,3276.0,0.0,78.0,360.0,1.000000,0.0

In [116]:
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier

#selector = RFE(RandomForestClassifier(random_state=1),
#                n_features_to_select=8,
#               step=.05)

#selector.fit(X,y)

#X = X.loc[:, X_columns[selector.support_]]
#print('Xshape:(%i,%i)' % X.shape)
#X.head()

Xshape:(614,8)

C:\Users\apple\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

,Dependents,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,0.0,1.0,5849.0,0.0,146.412162,360.0,1.0,0.0
1,1.0,1.0,4583.0,1508.0,128.000000,360.0,1.0,1.0
2,0.0,0.0,3000.0,0.0,66.000000,360.0,1.0,0.0
3,0.0,1.0,2583.0,2358.0,120.000000,360.0,1.0,0.0
4,0.0,1.0,6000.0,0.0,141.000000,360.0,1.0,0.0

In [117]:
#X_s = X_s.loc[:,X_columns[selector.support_]]
#print(X_s.shape)
#X_s.head()

(333, 8)

,Dependents,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,0.0,1.0,5720.0,0.0,110.0,360.0,1.000000,0.0
1,1.0,1.0,3076.0,1500.0,126.0,360.0,1.000000,0.0
2,2.0,1.0,5000.0,1800.0,208.0,360.0,1.000000,0.0
3,2.0,1.0,2340.0,2546.0,100.0,360.0,0.842199,0.0
4,0.0,1.0,3276.0,0.0,78.0,360.0,1.000000,0.0

In [21]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# holdout
X_train,X_test,y_train,y_test=train_test_split(X,
                                               y,
                                               test_size=0.2,
                                               random_state=1)
# set pipelines for different algorithms
pipelines = {
    'knn':
        Pipeline([('scl',StandardScaler()),
                  ('est',KNeighborsClassifier())]),
    'logistic':
        Pipeline([('scl',StandardScaler()),
                  ('est',LogisticRegression(random_state=1))]),
    'rsvc':
        Pipeline([('scl',StandardScaler()),
                  ('est',SVC(C=1.0,kernel='rbf',class_weight='balanced',random_state=1))]),
    'lsvc':
        Pipeline([('scl',StandardScaler()),
                  ('est',LinearSVC(C=1.0,class_weight='balanced',random_state=1))]),
    'rf':
        Pipeline([('scl',StandardScaler()),
                  ('est',RandomForestClassifier(random_state=1))]),
    'gb':
        Pipeline([('scl',StandardScaler()),
                  ('est',GradientBoostingClassifier(random_state=1))]),
    'mlp':
        Pipeline([('scl',StandardScaler()),
                  ('est',MLPClassifier(hidden_layer_sizes=(8,16),
                                       max_iter=100,
                                       early_stopping=True,
                                       random_state=1))])
}
# fit & evaluation
scores = {}
for pipe_name, pipeline in pipelines.items():
    pipeline.fit(X_train, y_train)
    scores[(pipe_name,'train')] = f1_score(y_train, pipeline.predict(X_train))
    scores[(pipe_name,'test')] = f1_score(y_test, pipeline.predict(X_test))

pd.Series(scores).unstack()

C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

              test     train
gb        0.590164  0.787402
knn       0.557377  0.666667
logistic  0.571429  0.596491
lsvc      0.542857  0.625899
mlp       0.591549  0.573643
rf        0.562500  0.966443
rsvc      0.516129  0.708661

In [20]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

pipeline = Pipeline([('scl', StandardScaler()),
                     ('est', GradientBoostingClassifier(random_state=1))])

parameters = {
        'est__n_estimators' : [20,30,40],
        "est__max_depth":[6,8,9],
        'est__min_samples_split' : [3,5,7],
        "est__learning_rate": [0.08, 0.1, 0.12],
}

gradient_boosting = GridSearchCV(pipeline, parameters, scoring='f1', cv=3, )
gradient_boosting.fit(X, y)
 
print(gradient_boosting.best_estimator_)
print(gradient_boosting.best_score_)

Pipeline(memory=None,
     steps=[('scl', StandardScaler(copy=True, with_mean=True, with_std=True)), ('est', GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=8,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0...    subsample=1.0, tol=0.0001, validation_fraction=0.1,
              verbose=0, warm_start=False))])
0.593229315166367

C:\Users\apple\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)

In [35]:
pd.DataFrame(gradient_boosting.cv_results_)[40:45]

C:\Users\apple\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split2_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('mean_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('std_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_est__learning_rate,param_est__max_depth,param_est__min_samples_split,param_est__n_estimators,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,mean_train_score,std_train_score
40,0.0416,7.353895e-03,0.0000,0.000000,0.1,8,5,20,"{'est__learning_rate': 0.1, 'est__max_depth': ...",0.542056,0.540000,0.642857,0.574861,0.047971,18,0.971888,0.919831,0.950820,0.947513,0.021380
41,0.0624,1.123916e-07,0.0000,0.000000,0.1,8,5,30,"{'est__learning_rate': 0.1, 'est__max_depth': ...",0.581818,0.549020,0.649123,0.593229,0.041641,1,0.996078,0.976000,0.980080,0.984053,0.008665
42,0.0312,0.000000e+00,0.0000,0.000000,0.1,8,7,10,"{'est__learning_rate': 0.1, 'est__max_depth': ...",0.525253,0.505263,0.642202,0.557435,0.060348,44,0.857143,0.769231,0.872247,0.832873,0.045423
43,0.0416,7.353895e-03,0.0052,0.007354,0.1,8,7,20,"{'est__learning_rate': 0.1, 'est__max_depth': ...",0.524272,0.505051,0.626087,0.551682,0.053068,59,0.946502,0.872247,0.946502,0.921750,0.035004
44,0.0676,7.353951e-03,0.0000,0.000000,0.1,8,7,30,"{'est__learning_rate': 0.1, 'est__max_depth': ...",0.533333,0.525253,0.638655,0.565628,0.051618,30,0.980080,0.955102,0.980080,0.971754,0.011775

In [38]:
from sklearn.model_selection import GridSearchCV

pipeline = Pipeline([('scl',StandardScaler()),
                     ('est',RandomForestClassifier(random_state=1))])

parameters = {
        'est__n_estimators'      : [5,10,15],
        'est__min_samples_split' : [2,5],
        'est__max_depth'         : [5,10,15],
        
}

random_forest = GridSearchCV(pipeline, parameters, scoring='f1', cv=3)
random_forest.fit(X, y)
 
print(random_forest.best_estimator_)
print(random_forest.best_score_)

Pipeline(memory=None,
     steps=[('scl', StandardScaler(copy=True, with_mean=True, with_std=True)), ('est', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=5,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=1, verbose=0, warm_start=False))])
0.5851450487150757

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

pipeline = Pipeline([('scl',StandardScaler()),
                     ('est',LogisticRegression(random_state=1))])

parameters = {
        'est__C'      : [0.1,1.0,10.0,100.0],
        'est__penalty' : ['l1','l2'],
}

logistic_regression = GridSearchCV(pipeline, parameters, scoring='f1', cv=3)
logistic_regression.fit(X, y)
 
print(logistic_regression.best_estimator_)
print(logistic_regression.best_score_)

C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\apple\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

Pipeline(memory=None,
     steps=[('scl', StandardScaler(copy=True, with_mean=True, with_std=True)), ('est', LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l1', random_state=1, solver='warn',
          tol=0.0001, verbose=0, warm_start=False))])
0.5817287932300166

In [51]:
mlp = Pipeline([('scl', StandardScaler()),
                ('est', MLPClassifier(hidden_layer_sizes=(8,16), max_iter=100, early_stopping=True, random_state=1))])
mlp.fit(X_train, y_train)
print(f1_score(y_train, pipeline.predict(X_train)))
print(f1_score(y_test, pipeline.predict(X_test)))

0.5736434108527132
0.5915492957746479

In [21]:
#imbalanced data
from sklearn.model_selection import train_test_split
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler,SMOTE

# holdout
X_train,X_test,y_train,y_test= train_test_split(X,
                                                y,
                                                test_size=0.20,
                                                random_state=0)
# resampling
rus = RandomUnderSampler(random_state=0)
ros = RandomOverSampler(random_state=0)
smt = SMOTE(random_state=0)

X_train_under, y_train_under = rus.fit_sample(X_train, y_train)
X_train_over, y_train_over = ros.fit_sample(X_train, y_train)
X_train_smt, y_train_smt = smt.fit_sample(X_train, y_train)

In [22]:
pipeline = Pipeline([('scl',StandardScaler()),
                     ('est',GradientBoostingClassifier(random_state=1))])


pipeline.fit(X_train, y_train)
print('Original Train:', f1_score(y_train, pipeline.predict(X_train)))
print('Original Test:', f1_score(y_test, pipeline.predict(X_test)))

#undersampling
pipeline.fit(X_train_under,y_train_under)
print('Undersampling Train:', f1_score(y_train_under, pipeline.predict(X_train_under)))
print('Undersampling Test:', f1_score(y_test, pipeline.predict(X_test)))

#oversampling
pipeline.fit(X_train_over, y_train_over)
print('Oversampling Train:', f1_score(y_train_over, pipeline.predict(X_train_over)))
print('Oversampling Test:', f1_score(y_test, pipeline.predict(X_test)))

#SMOTE
pipeline.fit(X_train_smt, y_train_smt)
print('SMOTE Train:', f1_score(y_train_smt, pipeline.predict(X_train_smt)))
print('SMOTE Test:', f1_score(y_test, pipeline.predict(X_test)))

Original Train: 0.7924528301886792
Original Test: 0.5454545454545454
Undersampling Train: 0.9337748344370861
Undersampling Test: 0.6341463414634148
Oversampling Train: 0.9087999999999999
Oversampling Test: 0.59375
SMOTE Train: 0.9025974025974026
SMOTE Test: 0.6296296296296297

In [23]:
gradient_boosting.fit(X_train_under, y_train_under)

GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=Pipeline(memory=None,
     steps=[('scl', StandardScaler(copy=True, with_mean=True, with_std=True)), ('est', GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0...    subsample=1.0, tol=0.0001, validation_fraction=0.1,
              verbose=0, warm_start=False))]),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'est__n_estimators': [20, 30, 40], 'est__max_depth': [6, 8, 9], 'est__min_samples_split': [3, 5, 7], 'est__learning_rate': [0.08, 0.1, 0.12]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='f1', verbose=0)

In [24]:
print('Undersampling Train:', f1_score(y_train_under, gradient_boosting.predict(X_train_under)))
print('Undersampling Test:', f1_score(y_test, gradient_boosting.predict(X_test)))

Undersampling Train: 1.0
Undersampling Test: 0.5063291139240507

In [25]:
pipeline.fit(X_train_under,y_train_under)
print('Undersampling Train:', f1_score(y_train_under, pipeline.predict(X_train_under)))
print('Undersampling Test:', f1_score(y_test, pipeline.predict(X_test)))

Undersampling Train: 0.9337748344370861
Undersampling Test: 0.6341463414634148

In [43]:
Y_proba = gradient_boosting.predict_proba(X_s)[:,1]

In [44]:
Y_proba.shape

(333,)